// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ4lqQ2Vpj_kGBO1z3xHFIUS-KIQzaWak',
    appId: '1:1265015426:web:fa91cd0d5e05701cf8729b',
    messagingSenderId: '1265015426',
    projectId: 'nurse-ease-fire',
    authDomain: 'nurse-ease-fire.firebaseapp.com',
    storageBucket: 'nurse-ease-fire.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqV2vKp8-fG_DBjAIzqFJ521Wglw_TDjI',
    appId: '1:1265015426:android:510a0c36732ceb51f8729b',
    messagingSenderId: '1265015426',
    projectId: 'nurse-ease-fire',
    storageBucket: 'nurse-ease-fire.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjHzUNNUjPQc7HBgCXWSPS1osLdiJ_Cm4',
    appId: '1:1265015426:ios:a0b0453fc5c7b7b4f8729b',
    messagingSenderId: '1265015426',
    projectId: 'nurse-ease-fire',
    storageBucket: 'nurse-ease-fire.firebasestorage.app',
    iosBundleId: 'com.example.nursingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjHzUNNUjPQc7HBgCXWSPS1osLdiJ_Cm4',
    appId: '1:1265015426:ios:a0b0453fc5c7b7b4f8729b',
    messagingSenderId: '1265015426',
    projectId: 'nurse-ease-fire',
    storageBucket: 'nurse-ease-fire.firebasestorage.app',
    iosBundleId: 'com.example.nursingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ4lqQ2Vpj_kGBO1z3xHFIUS-KIQzaWak',
    appId: '1:1265015426:web:0df83ddc4e9afbd0f8729b',
    messagingSenderId: '1265015426',
    projectId: 'nurse-ease-fire',
    authDomain: 'nurse-ease-fire.firebaseapp.com',
    storageBucket: 'nurse-ease-fire.firebasestorage.app',
  );
}
